#!/usr/bin/env python3

import logging
import sched
import time



def displayTopHits(aInStartTime, aInEventName):
    nowTime = time.time()
    elapsed = int(nowTime-aInStartTime)
    print("EVENT: {} name={} elapsed={}".format(time.ctime(nowTime), name, elapsed))



def begin():
    print("In Begin")
    scheduler = sched.scheduler(time.time, time.sleep)

    startTime = time.time()
    print("START TIME = " + time.ctime(startTime))
    scheduler.enter(5, 1, displayTopHits, (startTime, "displayTopHits"))

    scheduler.run()


if __name__=="__main__":
    logging.info("Starting HTTP Monitor")
    begin()
